### ISSUE TITLE
complement sequence on reverse strand.

### ISSUE THREAD

**Issue by yannickwurm** [pjotrp/bioruby-gff3-plugin#1]
Hi Pjotr,
thanks for making this happen. 
I may have encountered a bug.  In the following gff, my genes of interest are on the reverse strand (my genes of interest are those with "Vg" in the name)
http://fourmidable.unil.ch/temp/Si_gnF%2Escaffold10535-splittingyw.gff
(the GFF was first built by MAKER, and then manually edited using Apollo)
(my connection is slow here so the upload may take another 10 mins or so)

My sequences come out looking like this: 

> Si_Vg3-RA Sequence:Si_gnF.scaffold10535_2342963:2350091 (2342963:2350091)
> TACACCAAGGGACAGCAGGAAGAGAATGAACCACTCATGTGTAGTCGAAACGCTTATCATTGTCAAAAATGCGCTTTTAAAGTTCATCAGAAGTTTATTAGAACATGAAATTAATTTGAAAGCTTTATTTTAACAAACTGAACCATATTTTAGCTAATTATATGTAGATAATATTAACAACGTTTTAGACTTAAAGTGTAAAACGTGTATGAATAATTTAATTTAGTTCGGTCCGAAAAACTCTGTTATATTATGCACTTTATTAAAAGTGAATTCCCTTTAAAGTTAAGTTAGACTGTTTTTTATGTTCAAGGTTAATAATATTAAACTAGTAAAGAAACAGACCGTCAGCCGCACCGGCATCGGTACGGACTGGTGCTCGTACGGACCCTTGGCGTCTTGCTCATAGTTATGAGACATAAGCAAGCCTGTGACTGACCACACCTGTGCAACTTTGTCGTTATATGACCTTAAGTTAATTTCCCACAAGAGCAGTAAGTTCATTTTAGTCTCCTCAACAACGTTCGCTTCATATAGTTAGGTGCTATACGAGTATATGTGGTTCTTAATAGCTTGCCAGGCATAAGGTTCTAAGGACTTCTCTTAGAGCTTATAGCGCTATATGGGTACAGCCCTTTCGGTAAACTCTAGTTCAACTTCGTGCCTCACTAGGCCCTAAATAATAAGCTAGCATTGCATGGATGAACCCTCCACTTATACGAGTTCCCATAGCATCCAGTCGACGTCTAGCTGTGAGTCCCGCTTTTGCGCTATCTATCGGTCTCATGAGTCTAAGGGAGGTTGAGTCTCGGAAGAAGGCGATGCAAATTTCGGTACCTCCTAAGGCAGCCACCGTTTACGCTCCAAGATATACTCTAATGCGGCAACGGGGTTGTACATCGGGTTTGCTCCGGTCTATCTCATGGATACAGCAGACATGGGTCGTTTCCAGTAGTAATACTTCAATTCTTCAACTTCTTAATACTCTTCACGGTCCTCGCTGTCGAGATGGTAATGCCATACCTGCAATTTTACTGCTTCCTTTTATACTACTTTGCTTTATTTCAACAAAGCCATTCAATATATATAAAATTAACCATAGATATAAAATGACTATTAATGAAAGAATAAGATATTAGATCAATTTGTTACACTACTGACATTAACAACTTTTAATACTTTGTATGTAAATACTTTCTAATACTTTCTTTTCTTTGCCCTTTGATAAAATAAAATAAAATTTATAGCCATGAAACAGTATATGCCCCAACAGGTTTAATGTAACGTTGGTCTCTTACTATGCTATATATCTGCTTTGAATAAACTTTAACATACTAACAATGTCCTTAATAGGTGCTGAGTGTATCAATAGTGCCCATGGAACTTTTCAAAGTGGTAAGTTAGATGACTCTACTTCTTGCTCTATTGGCAAGTTGGACTTAGTAGGCTAAGAGGGTAACCATGACAGATGTCATATTGCTTTAATTGAAACCGGTTTTATTTGTTTTAGAGGTTGAGAACCAAACCTGGTGAGCTTAATTCGTTGCAGCTCAGTTGACCTTTAGACCACATGTATAAATTATTAGGAAAGAGACTAAGGCTCGTCGCTTCTCATCCAGTCGGCTCGTAATCAGCTTTAAGGCTCGTTCTTTTGAGAAATCTCTGGTTTTTTTCTAGAAAGGTGTCAGTGTCAAGGAGTAGGTCATCGAGATCATCAAGGTCGTCGCTCCTTCTTTTACTTAGACAGTACGTTAGATTCCGCAGTAATGCTTTGTAAAAGTACCGAGGCTTGCAGGGCGACAATGGAATGAAATAGCCAAAGTTTCCGTTCTGCTAGTACTTTAGATTACTCGTGTTGCAATACGTTGAACGGTTCCTGAATGAAGAGGTTTATCGATTTCTTTATGTCTTAGGAAGACTTCCTATACTCTTATGCGACCTCTTTATACATTTGAATTTCTTAGAGTAAGCGTGGTACCTAGCGTTCGTCATGTGACTCAATCTCGTTATACATAGGGTTAAATTATTCCGTTGTCACCTTCCGCTTTTACGAACCATGTGGAATGCGCTACGACAGCATGTACGACCTTGACCTGGACGAAAACAGTGATAGCTTTTAACCGATTTCTCACCTGTTCAATTTCCGCTTCTCCGCCGTCTTGAGGAAAGATTTTAAGGGTTTTCGCAAGTGGTTGGTTGTGGCCTAATATAGTTTCTTAAGAAACATTCATAGGTAAATACGTGTAAGTATTAATATCAAGGTCTCAGCTAACGTTGTAAATGAATTTGTAGTTTTGAAAATCTCTTCTCATATACTTTAGCCGGTTTTAACCGTAGTTCGCCTTTAGATTTTCTAATTAAGGTGTCACAAAAGAACTACACATACTTTCTCTTTTTATAATTAATATTTTAATTCAAACATATATAAAATTATATATATAAATGCGAATAAAAATCTAATGTAAAATGTATGTCTAAATATGTGTTGCTGTTCAAAATTATTTTCCTGTTTAAATTTTTTTTTGCGTTATAGAAAACAATTTTGAATATGACAACACATATTCACATACGTTTTATATAAACTTTTATTCGTATTTACATATATAATTTTATGTTCAGTCTATTATAATGTTTTTATTTTTTTTCAACTTGTATTATAGTTCATAATGCATAAAACATATTGTAAAAAAACAATAGTTGTTAAAAGACGCGTGAAAGGCCATAATGTTTATAATAAAAAGAGAAAGTATATGTAGTTCTTTGTGACACCTTAATTAAAAAATCCAAAGACGAACGCCGATTAAAATTGAACTCATAAGTAAATATGTCTTATTGGAATTCTGAGTTCGTAAAAAATTAAGAAAAATTGGTTAAGTTTATAAATAATAATTTTTAATATATTTTTTTAATAAAAATTAAAATTTTAAACGTATTAAATTAGACACGTCTTTGACTAATTCTCAAGTCACCATTGAGTTGTTCTTATGCATTTACACAGGCGTGGAGATCGTAAACGACTTGACAATGCGTTATTAATACAGCAGGGTAGAATGATAGGCCATGTGTCAAAGCCGGCATACTGAGAATTCCCTTTACTTCTCTATCTGTTGATATAAAGAATAAACCGATTGGTTAACGTTGTTCCGATGGAGCTTTTGTTATGAGTCTTTTAAGTCTGTAAGTAGAAACGTGAACCACAGTGACGGGTAGGCTTCTAATAGAGTCAGAAACTCGGTATGAATCTTCCGTTCGACGGCTGCTGCTTTATAGTTGCATACGAGTACCACCGGCGAGACATACTAGATAGGTCTCTGTATGGTTTTAATCAACCTGGTTAAAAGATATTCGAGATGTACTTACTTTTGCTTCGAGTGCTTCAAGCAACGTACCGTCATGTCGTTAAATAGGACTGTCTGGGCGGTTACTAATGCAACGTTGCGCATCGCTTTATGTGATTAATGCTAGTCTCACTAGTCCACTTGAGACGGCACTTCTCATGCGATTTGTCGTAGTAATTATGCTTCGCTGGCCTTACCGCTTTAGAGCGATTGTTCCGCGCGTCACAGTCCATAGATCACTTAGGTTTCTTGATACTGTGGACCATGAGCTTCCCGATGATATATCTAAAACTTTTGACCCAAAAGTTTCCTGAATTACACTTTTACCAACGATCATTACTACGGCATGATGGGTCTATACATATGCAACCGGAACTATCATAAAAGTTGAAGGAGGCATTCGGGTGAAAGCTTCATCCTATACGCCATAGCTCGATGTCCGTCCAAATGCTAAACTAGTTACTCAACACCTTGAGGATAGTTAAACTTCTTTACTCTCTCTTTAGTGTTCCTAGTGCGCAACTCTTTGATCGCGTTCTTGAATTCTAATTTAGGCCTGTCTTCTTATTAAACCTTCCTGTACAGGACAAATTGAGCCATATGCCAAGGTACCAGATAGGAATGCTGTTCGTATCTTAATCTCTCCGGCAACGACCACTCATAGAACTTGAAATGAAGTTTTAGTATAATGAATGTTTCTATAATTAATAATAATGTAACGTCGCGACTTTTTTGAAGACTGCTCACTGAGGTTTGACTTTTGTTGACGTAAATTGTTAAAGCTTTTCTATCACTCGAAGGGCTACCTTTACCCACACGGCAAGCAGATAAGAAAGCTCGACGGTCATAAACATTTTTCACTTTAATTGAAATTTTTTCCTCTTGGGTAGTGGAGCTCCTCACCGCAAATGCTTTGCAATAAGACGTTATCTCATGTCTTCGCCAAACCAAAGTATCGTGGAAAGCTCATAGTCTTAATATAACGACCATAACTGTTTTTACCTTATTACGCTCATGGAGATTTTATGCTTTGGTTATAACTATATTTTGTCTTTTTGAAACGTAACTTCTAAGTAGGCTTGTATGGCGTTAGACCTTGCTCATGACCTAATTGTGTAATATCACAGCAAGGGAAGTGGTGCGCTGTTTTATAGAAATTAGAAGTTGGTCATAGATTACTCCCATTATGCGCAGGACACTATTGGAGTCTTTATGTATTTTACTGTTTTCTTTTTCCAGGTAAAAGATAGTTTTATCTTAGACTATGGTGCTTTTTTCTTAGTCAGAACCTTCTATAGCAATGCCCTTAGAGCTTTAGTAGATTAAGATTATTGCTCGCAATATACTTTTATCTGTGTTGTAAACTCAGATTCGTTCATCGTTTCACACTCTATGTTTAGCTGTACTGCAAGCTACGTCACTGTTAAGTGCCATTCTTAGTCGTTGGTAGCGTATTTCTCTACGTTGTGGTGTCATTTGACCTAACCTTTGGTTTGTCATTCCTTTCTTCTCTTCTTTAACATTTACAGGAGTCGCGTCCAGAGTTCAGCCCATGTCAGAAACATCGCCTGCATTCAAAGTCAGAGGGCTCCAATGTTCTGTTGTGAATACAAAAATGACAGCCGTCGCACTCTTCATTATATCTGGTCTTTAATTCTGTAATGAAAATACAATTATGATTACGTCGCGTTCTTCATTTTATACTTGAAACAATGAGTGTTCTTCATGTTATACGTATAGGATGAGGAGAGTTAAAGCTTATGCGGTAATTATTGCTTGGTTTTCTATTTAATTTCCCACATAACGCTATACCTTCTTGGACGTTATGTCCTTTACTTTAACAATAGTGGCCTTCGAGGAGTGTTTCAGGTGTTGACTCTCTATACTATCTCTTGAGGTCGTAATGGTTTGTTACATACCTTCTCTAAGTTTTCCCTTTCTTTAGACACGCTTGAACGTTATTCCGATGACTGCAACGGGTTCACTCCCTAGTCGATTTGAAAGTATAACTACGTAGGGTCGAAAGACTTTATGCGGTCTTTATACTGGTCCACTAGCCAGAGGAGTTAATATGCTTAAATAGTGTTATGTTACAAGTCGTTTTGAGACTTTGGTTGTGGTAGCAACATGTTTTGGGTACCCACTACCATGGTTGGCATGTTCTCGGCACCATGGCAACCCGGTAATTTGGAAGTCTTAGTGTTTCCGTTTCACTTTAACTACAGGACAATCTGCTTCATAGTGTTGCATTCAATGTTTTAAAACATTTTTGTTATTAATTATAAAAAATTAACAAATTCATAATTTTCTGCATTACCATTGATATAGATATACATTACTATTATTAAATACACAATTAATTCTTAGTTTAATTACGAGTTTATTACAGCGTCTTCGAGATTAGAAGATTTGAGATCTGAAACATCGTAAAGTATTAATATAAAATTTATTAAATTTATTAACATCAAGTTTACTTCATTTATTAACAAGATAGTAATCAAAAGCTACGTAATATAGATTGACTCATTTGAGAGAATACTTTACATTACATCTTATAGATAGTTTCAGAGTATATTAAATTGTAGTGACTTAAGAAAAAATGTCGAAGCACGTGAGAGCTATTGCTGTTCTAAGAATGAAAACTATTGGTCGAGATATTGCACGTTGATCCTTTTACATTCGTGCACGAAAATTGGTGGATAGGTGTTCTAAGGGTATTAGCATCTTTAATATAAGGCCTTTCGAGCTTTCACCGACAGAATCGATTTCTATGCCTGTTACTGTCGTCTTTACAAATACATACCGACCCGTTAGATCTTTAACTTGACTTCTTTCACCCATTACTAGATTTTCAACGTTATTTGCCTGTCTTGCAGCTCTATGGCCTCTTTCCGGTAGTTCTTTCGTTACCTTTACTTTAGTAAAAGCTTTAGCACGTTAATGGTCTGCCTAGGGAGAGACAGTAAAGTCTCTTCATACCTTATTGGCAGTATAAGCTGCCTTTTGTGCAAGCTAATATACATTCATTTTTAGATTTTATTGAACTATTATAAAATTCATTAATTAATATTTGTCATGCTACCATGTTCTTTCACATTATTTTTAGCTTTATTTAAACAATGATCCGTTTACCACGTTGTATAGCATTACGGTATGCACCAGAGACGCCGTTGATGCTGAGGTCCGCACTATTGCTAAAGGAGTGAGGATTCTTGACAGAGAACTGCTTTGGCCTTCTTAAACGGCGATGGATGCGATACTGTTTGCTCTTAACGGTTCCTGGACGAGGCCTTTTATTTGCTTTTCGGCTTCCTCGGTACACGTAACTTCACGGTCTCGTCGTTGTCTACTTGCAATAGTCGCTGTCTCTTCGCCCATCTTACTACTGTCTCCCGCCTTTAACCCCGATGGTAGTCAGATTAGCGTTCTTTCTTGTACCTGTTCTATCATTTTCTCCAGTGCCAGTATTTTTTATGTTAGTCTTTCTGAGCGTCCTCCCACCTAGTTTGCTCTCAGTTATATCCTTCTTTGTGTTGTAACAGATAGCGTGCTCTCAACATCTTTACCTGCTATTTTAGACAAAGTGATGATGTGGACATGGTCCTACGGAGGTTCTATGGTCCGGGCATCTTTCTCAAGGCTTCTTTATACTAGAAATAACGGACAGCTTCTTGTTACTTAGATACCTGGAGTTTGCATCCCAGCTCCTTCCGCGATTCGGTCTAAAATGAGTTTTCGGACAGTTGTTCTATGTTTTGAAGGTTTAAGGACAGAGAACGTCGCGGCGTATT

(first three nucl are "TAC" which is the _complement_ of ATG). But it's not the reverse-complement either. So I think there is a snafu in there. These genes of interest are on the reverse strand. Maybe your parser forgets to take the complement?

Also, are you planning on letting users extract more generic labels? (eg: this gff has the "gene" label) 

Thanks!
yannick

**Comment by pjotrp** [comment]
Hi Yannick,

I am looking into the bug. More soon.

Pj.

**Comment by pjotrp** [comment]
Bug should be fixed. Also support for 'gene' type. Other types will come soon. Now available as gem.

**Comment by yannickwurm** [comment]
excellent!
